### ISSUE TITLE
Can it be global?

### ISSUE THREAD

**Issue by Globik** [NickNaso/addon-event-emitter#2]
Is it really useful? I think it is like phocus or magic, not very useful.
I mean every emmiter instance should be as a global variable, not in a function scope like you did.
Can it be globalish like this:
Napi::Function emit = nullptr; ?
It looks like no:
Napi::Function emit = info[0].As<Napi::Function>();
This emit should be global cuz from any part of code could be emit an event. Alas. Not in this case. As I understand info also can't be globalish. It is very pitty!
Just a phocus. You really emit an event from within node.js, not from cpp!!!
but should to do a real event from any part of cpp code workflow to node.js
Just like as if promises doing that.

And else one moment. I really don't undestand for what all developers using those f*** c++ wrapper when napi addons purposes to support pure C language?

**Comment by NickNaso** [comment]
This repo contains only some examples and maybe the are not useful in all scenarios. You're right it's possible implement a native emitter, but this is not the purpose of this repo. 
At the end N-API is written in C and here I used its C++ Wrapper because I want experiment on it.

**Comment by Globik** [comment]
Yup, it can be global.
If napi_create_reference(), napi_get_reference_value(), napi_delete_reference(), napi_get_global() to use. And also env to save into temporary env.

**Comment by Globik** [comment]
Who is wondering about how to achieve the same concept in plain C (based on example 00) here it is:

https://github.com/Globik/kore-mediasoup/tree/master/addon/emitter

**Comment by Globik** [comment]
Just playd around with example 00. Something fundamentally broken. It works fine if it is standalone. But if you will decide to add to code another one dummy napi method - for example hello world function, so workflows breaks after those emitter calls from cpp. Brings to segmentation falls. Sample 01 not tested.
